### ISSUE TITLE
USER STORY: Navbar

### ISSUE THREAD

**Issue by MilenTecle** [MilenTecle/znapped#1]
As a **user**, I can **access a navigation bar on every page** so that **I can browse between different sections of the app easily.**

### Tasks

- [x] Design and implement a responsive navigation bar that is present on all pages.
- [x] Ensure the links in the navbar redirect to the correct pages.
- [x] Highlight the current side the user is navigating on.
