### ISSUE TITLE
USER STORY: Sign Up

### ISSUE THREAD

**Issue by MilenTecle** [MilenTecle/znapped#3]
As a **user**, I can **create an account** so that I can **access features available only to registered users.**

### Tasks

- [x] Create a user registration form with validation.
- [x] Implement backend logic to store user credentials securly.
- [x] Ensure user gets redirected to sign in page after sign up.
