### ISSUE TITLE
USER STORY : Send messages to other users

### ISSUE THREAD

**Issue by MilenTecle** [MilenTecle/znapped#34]
As a **user**, I can **send a message directly to a user** so that **we can have separate conversation.**

### Tasks

- [x] Implement backend logic for direct messages
- [x] Add the message component to the frontend
- [x] Notify user when user has a new message
