### ISSUE TITLE
USER STORY: Sign In

### ISSUE THREAD

**Issue by MilenTecle** [MilenTecle/znapped#4]
As a **user**, I can **log in to my account** so that I can **use the functionality available to logged in users.**

### Tasks

- [x] Develop a login form that allows users to enter their credentials.
- [x] Set up middleware authentication to validate user credentials.
- [x] Ensure user gets redirected to home page when logged in.
